config/routes.rb
SampleApp110811::Application.routes.draw do
  resources :ratings

  resources :websites

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#home'
  match '/uindex', :to => 'users#index'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/windex', :to => 'websites#index'
  match '/rindex', :to => 'ratings#index'
  match '/createweb', :to => 'websites#new'
  match '/createrate', :to => 'ratings#new'
  match '/allweb', :to => 'websites#index'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  
  attr_accessible :user_id
  attr_accessible :website_id
  attr_accessible :score
  

  
  score_regexp = /\A[0-5]/i
  
    validates :score, :presence => true,
              :format   => { :with => score_regexp}
end

app/models/user.rb
class User < ActiveRecord::Base
  
  email_regexp = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50}
  
  validates :email, :presence => true,
                    :format   => { :with => email_regexp},
                    :uniqueness => {:case_sensitive => false}
                    
                    
end

app/models/website.rb
class Website < ActiveRecord::Base
  
  url_regexp = /\Awww\.[a-z]+\.[com|net|mil|edu|gov|org|biz|xxx]/i
  type_regexp = /\A[video|audio|games|programs|torrents]/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50}
                   
  validates :kind, :presence => true,
                   :format   => { :with => type_regexp}
             
  validates :url, :presence => true,
                  :format   => { :with => url_regexp},
                  :uniqueness => {:case_sensitive => false}
                  
  def rate(website)
    ratings.create!(:website_id => website.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
     @rating = Rating.new(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render json: @rating, status: :created, location: @rating }
      else
        format.html { render action: "new" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :ok }
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user.nil?
      flash.now[:error] = "Invalid email"
      @title = "Sign in"
      render 'new'
    else
      sign_in user
      redirect_to user
    end
  end

  def destroy
     sign_out
     redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new   # responds to get /users/new by rendering new.html.erb
    @title = "Sign up"
    @user = User.new
  end
  
  def create  # responds to post /users and redirects to /user/i if successful or new.html.erb if not
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_path(@user)
    else
      @title = "Sign up"
      render 'new'
    end
  end
  
  def show  # responds to get /user/i by rendering show.html.erb
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def index  # responds to get /users by rendering index.html.erb
    @title = "Current users"
    @users = User.all
  end
  def rate(website)
    rate.create!(:website_id => website_id)
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @websites }
    end
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
    @website = Website.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/new
  # GET /websites/new.json
  def new
    @website = Website.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/1/edit
  def edit
    @website = Website.find(params[:id])
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(params[:website])

    respond_to do |format|
      if @website.update_attributes(params[:website])
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /websites/1
  # PUT /websites/1.json
  def update
    @website = Website.find(params[:id])

    respond_to do |format|
      if @website.update_attributes(params[:website])
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website = Website.find(params[:id])
    @website.destroy

    respond_to do |format|
      format.html { redirect_to websites_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    image_tag("logo.png", :alt => "Kays App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
    def score(website)
    x=0
    n=0
    @rating = Rating.all
    @rating.each do |i|
      if (website.id.to_i == i.website_id.to_i)
        x=x+(i.rating.to_i)
        n=n+1
      end
    end
    if(n==0)
    n
    else
    x
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.id
    current_user = user
  end
  
  def sign_out
    cookies.delete(:remember_token)
    current_user= nil
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
      !(current_user.nil?)
  end

  private
    def user_from_remember_token
      userId = remember_token
      User.find_by_id(userId)
    end
  
    def remember_token
      cookies[:remember_token] || nil
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
  def this_website(website)
    $WS = website
  end
  def last_website
    $WS
  end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav>
			<%= link_to "About", about_path %>
			<%= link_to "Home", root_path %>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class ="round" >
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<% if signed_in? %>
			  <li><%= link_to "Profile", current_user %> </li>
			  <li><%= link_to "Sign out", signout_path %> </li>
			<% else %>
			   <li><%= link_to "Sign in", signin_path %> </li>
			<% end %>
	    </ul>
	</nav>
</header>

app/views/layouts/_login.html.erb
<login>
 <nav>
			<% if signed_in? %>
			  <%= link_to "Profile", current_user %> <br />
			  <%= link_to "Sign out", signout_path %><br />
			  <%= link_to "New Website", createweb_path %> <br />
			<% else %>
			   <%= link_to "Sign in", signin_path %>
			   <%= link_to "Register", signup_path %>
			<% end %>
 </nav>
</login>

app/views/layouts/_news.html.erb
<news></news>

app/views/layouts/_sidebar.html.erb
<sidebar>
<h3> Categories </h3>
<%= link_to "View All", allweb_path %>

</sidebar>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag    'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag    'custom', :media => 'screen' %>

app/views/layouts/_title.html.erb
<title>
<h1>		Web Surfer		</h1>
</title>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @title %></title>
		<%= stylesheet_link_tag    "cssmainpage" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
   </head>
   <body>
<div id="title"><%= render 'layouts/title' %><div id="login"><%= render 'layouts/login' %></div></div>
<div id="temp">
<div id="blank"></div>
<div id="sidebar"><%= render 'layouts/sidebar' %></div>
<div id="main"><%= yield %></div>
<div id="tools"></div>
<div id="footer"><%= render 'layouts/footer' %></div>
   </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<pre>	There are many websites out there with free content like games, videos, music, applications, source code, and more but unless they are extremely big or you do a lot of surfing you probablly don't know about them. This website was designed to help share the not so well know websites with the world. <br /></pre>  
<h2>How to use this site:</h2>
<pre>	If you are just looking for new websites to enjoy just browse this site for what you are looking for. If you happen to know a few sites and would like to share them or your opinion on them please sign up.</pre>

app/views/pages/home.html.erb
<h2>Welcome to Web Serfers</h2>

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  	<div class="field">
  		<% f.hidden_field :website_id, :value => last_website.id%>
 	 </div>
 	   	<div class="field">
  		<% f.hidden_field :user_id, :value => current_user.id%>
 	 </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>Website</th>
    <th>User</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.website_id %></td>
    <td><%= rating.user_id %></td>
    <td><%= rating.score %></td>
    <td><%= link_to 'Destroy', rating, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Website:</b>
  <%= @rating.website_id %>
</p>

<p>
  <b>User:</b>
  <%= @rating.user_id %>
</p>

<p>
  <b>Score:</b>
  <%= @rating.score %>
</p>

<%= link_to 'Back', ratings_path %>
<%= link_to 'Home', root_path %>

app/views/users/index.html.erb
<h1>Current users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/new.html.erb
<h1>WELCOME</h1>
<h4> Please fill out the information below </h4>
<%= form_for(@user) do |f| %>
  <div class="field" >
    <%= f.label :name %> 
    <%= f.text_field :name %>
  </div>
  
  <div class="field" >
    <%= f.label :email %> 
    <%= f.text_field :email %>
  </div>
  
  <div class="actions" >
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Account information</h1>
<p> <strong>Name:</strong> <%= @user.name %></p>

<p> <strong>Email:</strong> <%= @user.email %></p>

app/views/websites/_form.html.erb
<%= form_for(@website) do |f| %>
  <% if @website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% @website.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

1)Input either [video][audio][games][programs][torrents] for type<br />
2)Type only the base url www.NAME.com (no back slash at the end)

  <div class="field">
    <h1><%= f.label :name %></h1><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <h1><%= f.label :url %></h1><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <h1><%= f.label :kind %></h1><br />
    <%= f.text_field :kind %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/websites/_rate.html.erb
<%= form_for(current_user.ratings.build(:website_id => @website.id )) do |f| %>
  <div class="field">
  	<% f.hidden_field :website_id %>
  </div>
  <div class="field">
 	<%= radio_button_tag(:score, "0") %>
	<%= label_tag(:score, "0") %>
	<%= radio_button_tag(:score, "1") %>
	<%= label_tag(:score, "1") %>
	<%= radio_button_tag(:score, "2") %>
	<%= label_tag(:score, "2") %>
	<%= radio_button_tag(:score, "3") %>
	<%= label_tag(:score, "3") %>
	<%= radio_button_tag(:score, "4") %>
	<%= label_tag(:score, "4") %>
	<%= radio_button_tag(:score, "5") %>
	<%= label_tag(:score, "5") %>
  </div>
  <div class="actions">
  	<%= f.submit "Submit" %>
  </div>

<% end %>

app/views/websites/edit.html.erb
<h1>Editing website</h1>

<%= render 'form' %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/index.html.erb
<h1>Listing websites</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @websites.each do |website| %>
  <tr>
    <td><%= link_to website.name, website %></td>
    <td><%= website.url %></td>
    <td><%= website.kind %></td>
    <% if signed_in? %>
    <td><%= link_to 'Destroy', website, confirm: 'Are you sure?', method: :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
    <% if signed_in? %>
<h3><%= link_to 'New Website', new_website_path %></h3>
    <% end %>

app/views/websites/new.html.erb
<h1>New website</h1>

<%= render 'form' %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>
<% this_website(@website) %>

<h1><%= @website.name %></h1>

<h2><%= @website.url %></h2>

<h2><%= @website.kind %></h2>

<% if signed_in? %>

<p>
  <b>Rate:</b>
<%= link_to 'Rate this site', createrate_path %>
</p>

<p>
  <b>Score:</b>
  <%= score(@website)%>/5
</p>
<% end %>
<%= link_to 'Back', websites_path %>
<%= link_to 'Home', root_path %>